import type { ThemeManifest } from '@pasmello/shared';

export const manifest: ThemeManifest = {
    id: 'cute',
    name: 'Cute',
    version: '1.0.0',
    description: 'Pastel tones with floating navigation',
    builtIn: true,
    settings: [
        {
            key: 'accentColor',
            type: 'color',
            label: 'Accent Color',
            description: 'Primary accent color',
            default: '#f8a4c8',
        },
        {
            key: 'backgroundColor',
            type: 'color',
            label: 'Background Color',
            description: 'Main background color',
            default: '#fff5f9',
        },
    ],
    tokens: {
        '--pm-bg-primary': '#fff5f9',
        '--pm-bg-secondary': '#ffeef5',
        '--pm-bg-tertiary': '#ffe4ef',
        '--pm-bg-surface': '#ffffff',
        '--pm-accent': '#f8a4c8',
        '--pm-accent-hover': '#f58db8',
        '--pm-accent-subtle': 'rgba(248, 164, 200, 0.15)',
        '--pm-border': '#f0d0e0',
        '--pm-border-subtle': '#f5e0eb',
        '--pm-radius-sm': '12px',
        '--pm-radius-md': '16px',
        '--pm-radius-lg': '24px',
    },
    darkTokens: {
        '--pm-bg-primary': '#1a0f14',
        '--pm-bg-secondary': '#2a1a22',
        '--pm-bg-tertiary': '#3a2a32',
        '--pm-bg-surface': '#2a1a22',
        '--pm-accent': '#f8a4c8',
        '--pm-text-primary': '#ffeef5',
        '--pm-text-secondary': '#c0a0b0',
        '--pm-border': '#4a3a42',
        '--pm-border-subtle': '#3a2a32',
    },
};
